### ISSUE TITLE
GBA files likely not working

### ISSUE THREAD

**Issue by ihaveamac** [ihaveamac/pyctr#18]
Most likely an issue with pyctr, but someone reported that ninfs would not mount the content properly.

**Comment by ihaveamac** [comment]
This is because `ExeFSReader.decompress_code` fails with a GBA rom. With a valid 3DS codebin (compressed or decompressed) it exits just fine.
```py
>>> from pyctr.type import exefs as e
>>> a = e.ExeFSReader('exefs.bin')
>>> a.decompress_code()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyctr/type/exefs.py", line 308, in decompress_code
    code_dec = decompress_code(code)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyctr/type/exefs.py", line 126, in decompress_code
    byte = dec[ptr_out + seg_off]
IndexError: bytearray index out of range
```

**Comment by ihaveamac** [comment]
Best way to detect a GBA game seems to be to read the core version from the extheader (https://www.3dbrew.org/wiki/NCCH/Extended_Header#ARM11_Local_System_Capabilities). This would be best after an extheader reader is added. https://github.com/ihaveamac/pyctr/issues/2
